from __future__ import annotations


TOP_BAR_HEIGHT = 64
ENTRY_TABS_BAR_HEIGHT = 44
BOTTOM_BAR_HEIGHT = 96

COLOR_TOP_BAR_BG = "#F39A9A"
COLOR_TOP_NAV_BUTTON_BG = "#5F58C8"
COLOR_TOP_NAV_BUTTON_DISABLED_BG = "#8E88D8"
COLOR_WEEK_TILE_BG = "#F4A0A0"
COLOR_WEEK_TILE_CLOSED_BG = "#E6B7B7"
COLOR_WEEK_TILE_SELECTED_BORDER = "#4F46A5"
COLOR_WEEK_BLOCK_SUMMER_BG = "#F2ABAB"
COLOR_WEEK_BLOCK_WINTER_BG = "#E6B3C4"
COLOR_WEEK_BLOCK_BORDER = "#D98787"
COLOR_ENTRY_TABS_BG = "#EFEFEF"
COLOR_ENTRY_TAB_SELECTED_UNDERLINE = "#6D5BD6"
COLOR_CENTER_BG = "#E6E6E6"
COLOR_BOTTOM_BAR_BG = "#36B7E6"
COLOR_TEXT_PRIMARY = "#111111"
COLOR_TEXT_MUTED = "#555555"
COLOR_TEXT_DIMMED = "#7A6E6E"
COLOR_WHITE = "#FFFFFF"
COLOR_ERROR_TEXT = "#8A1F1F"
