[CmdletBinding()]
param(
    [string]$ServiceAccountJsonPath = ".secrets/firestore-mobile-rw.json",
    [string]$OutputDir = "build/apk",
    [string]$BuildVersion = "0.2.1",
    [int]$BuildNumber = 1
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Resolve-FirestoreProjectId {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoRoot
    )

    if ($env:FIRESTORE_PROJECT_ID -and $env:FIRESTORE_PROJECT_ID.Trim()) {
        return $env:FIRESTORE_PROJECT_ID.Trim()
    }

    $envFilePath = Join-Path $RepoRoot ".env"
    if (-not (Test-Path $envFilePath -PathType Leaf)) {
        return $null
    }

    foreach ($line in Get-Content $envFilePath -Encoding UTF8) {
        if ($line -match "^\s*(#|$)") {
            continue
        }
        if ($line -match "^\s*FIRESTORE_PROJECT_ID\s*=\s*(.+?)\s*$") {
            $candidate = $matches[1].Trim()
            if (
                ($candidate.StartsWith("'") -and $candidate.EndsWith("'")) -or
                ($candidate.StartsWith('"') -and $candidate.EndsWith('"'))
            ) {
                $candidate = $candidate.Substring(1, $candidate.Length - 2).Trim()
            }
            if ($candidate) {
                return $candidate
            }
        }
    }

    return $null
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $repoRoot

$serviceAccountPath = if ([System.IO.Path]::IsPathRooted($ServiceAccountJsonPath)) {
    $ServiceAccountJsonPath
}
else {
    Join-Path $repoRoot $ServiceAccountJsonPath
}

if (-not (Test-Path $serviceAccountPath -PathType Leaf)) {
    throw "No existe el JSON de cuenta de servicio: $serviceAccountPath"
}

$firestoreProjectId = Resolve-FirestoreProjectId -RepoRoot $repoRoot
if (-not $firestoreProjectId) {
    throw "No se pudo resolver FIRESTORE_PROJECT_ID desde entorno ni desde .env."
}

$serviceAccountJson = Get-Content $serviceAccountPath -Raw -Encoding UTF8
try {
    $null = $serviceAccountJson | ConvertFrom-Json
}
catch {
    throw "El archivo de cuenta de servicio no es JSON valido: $serviceAccountPath"
}

$serviceAccountJsonB64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($serviceAccountJson))
$projectIdLiteral = $firestoreProjectId.Replace("\", "\\").Replace("'", "\\'")
$jsonB64Literal = $serviceAccountJsonB64.Replace("\", "\\").Replace("'", "\\'")

$mobileSecretsPath = Join-Path $repoRoot "src/frosthaven_campaign_journal/config/_mobile_runtime_secrets.py"
$mobileSecretsDir = Split-Path -Parent $mobileSecretsPath
if (-not (Test-Path $mobileSecretsDir -PathType Container)) {
    New-Item -ItemType Directory -Path $mobileSecretsDir | Out-Null
}

$mobileSecretsModule = @"
# Generated by scripts/build-android-with-mobile-secrets.ps1. Do not commit.
FIRESTORE_PROJECT_ID = '$projectIdLiteral'
GOOGLE_APPLICATION_CREDENTIALS_JSON_B64 = '$jsonB64Literal'
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

try {
    [System.IO.File]::WriteAllText($mobileSecretsPath, $mobileSecretsModule, $utf8NoBom)

    $env:FLET_CLI_NO_RICH_OUTPUT = "1"
    pipenv run flet build apk . --yes --no-rich-output --skip-flutter-doctor -o $OutputDir --build-version $BuildVersion --build-number $BuildNumber

    $outputRoot = if ([System.IO.Path]::IsPathRooted($OutputDir)) {
        $OutputDir
    }
    else {
        Join-Path $repoRoot $OutputDir
    }

    $canonicalApkPath = Join-Path $outputRoot "frosthaven_campaign_journal.apk"
    if (Test-Path $canonicalApkPath -PathType Leaf) {
        $apkPath = (Resolve-Path $canonicalApkPath).Path
    }
    else {
        $latestApk = Get-ChildItem $outputRoot -File -Filter *.apk | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        if (-not $latestApk) {
            throw "No se encontro ningun .apk en: $outputRoot"
        }
        $apkPath = $latestApk.FullName
    }

    $apkHash = Get-FileHash $apkPath -Algorithm SHA256
    Write-Host "APK generado: $apkPath"
    Write-Host "SHA256: $($apkHash.Hash)"
}
finally {
    if (Test-Path $mobileSecretsPath -PathType Leaf) {
        Remove-Item $mobileSecretsPath -Force
    }
}
